### ISSUE TITLE
Ubuntu Software Center

### ISSUE THREAD

**Issue by astoilkov** [jordansissel/fpm#1078]
I am creating `.deb` package with `fpm`. However, I have few questions regarding that:
 - After I open the created `.deb.` package an information gets merged with an already existing package in the Ubuntu Software Center and the icon, total size and license are incorrectly taken from the already existing package in Ubuntu Software Center. This is caused from the fact that both applications have the same name. Do you know how fix this?
 - Is there any way to set an icon for the `.deb` package to be shown when opened in Ubuntu Software Center?

**Comment by hatt** [comment]
I'll answer these in reverse order since it's easier. The icons in the Software Centre are predefined in another package managed by Ubuntu, there is no way to choose a specific icon for your package. The package which manages these icons is `app-install-data` and comes as part of the Ubuntu desktop.

I think the merging of package data is a bug in Ubuntu Software Centre though. It's somewhat common to have different packages with the same name in Debian systems, you normally just prioritise one repo over another. It sounds like Software Centre doesn't know how to prioritise user added packages properly.

Not much we can do about either of these in FPM unfortunately.

**Comment by astoilkov** [comment]
Thank you very much for this detailed description. I had to rename my package in order to get this working.

Do you know any straightforward way to include a new package in the Software Center database?

**Comment by hatt** [comment]
The easiest way, besides for manually opening stuff in the Software Centre, would be to add a local directory as a repository. Ubuntu has [pretty good documentation](https://help.ubuntu.com/community/Repositories/Personal) for it. There is a bit of CLI work involved but that's the easiest I know of. Possibly there are some graphical tools that you can just point at a directory and they'll manage your `apt.sources` for you.

Renaming was a bit of a silly but easy workaround, however I still think this is a bug in Software Centre. Unfortunately I don't have an Ubuntu desktop machine to test it on at the moment though.
