### ISSUE TITLE
[deb] Asking for configuration variable

### ISSUE THREAD

**Issue by waghanza** [jordansissel/fpm#1079]
Hi,

Using `fpm` to build my package. 
I need to set configurations variable on to start my application.
To be precise, it's an application that connect to a database that provides a **REST** api (like https://github.com/begriffs/postgrest does).
I was wondering if `fpm` let me ask the `installer` to provide a `DSN` (via a tui window) that could be written to a file (or else).

Regards,

**Comment by hatt** [comment]
I believe this function is part of Debconf, specifically the `db_input` declarations. I'm not sure if this generates the TUI or GUI or whether it goes in the control file, an alternate file, or the pre/post-install files but since it's done during install I expect it's not the script runners. From what I can tell, it's just a template file we drop into the package. Right now, this is not possible for FPM, but it seems very doable.
