### ISSUE TITLE
Perl CPAN to RPM is not including dependency requirements in target package as it should

### ISSUE THREAD

**Issue by liger1978** [jordansissel/fpm#1114]
```bash
[vagrant@localhost vagrant]$ fpm -t rpm -s cpan --no-cpan-sandbox-non-core --no-cpan-test Fennec
```

This should produce an RPM with a number of `perl-xyz` dependencies, but it does not:

```bash
[vagrant@localhost vagrant]$ rpm -qpiR perl-Fennec-2.017-1.noarch.rpm
Name        : perl-Fennec
Version     : 2.017
Release     : 1
Architecture: noarch
Install Date: (not installed)
Group       : default
Size        : 223993
License     : perl_5
Signature   : (none)
Source RPM  : perl-Fennec-2.017-1.src.rpm
Build Date  : Mon 16 May 2016 03:07:54 PM UTC
Build Host  : localhost
Relocations : /
Packager    : <vagrant@localhost.localdomain>
Vendor      : Chad Granum <exodist7@gmail.com>
URL         : http://exodist.github.io/Fennec/
Summary     : A testers toolbox, and best friend
Description :
A testers toolbox, and best friend
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(CompressedFileNames) <= 3.0.4-1
```

**Comment by liger1978** [comment]
Anyone else seeing this?

**Comment by BaxterStockman** [comment]
@liger1978 -- I am seeing it as well.  It appears to be due to more modules moving to version 2 of the [CPAN metadata specification](http://search.cpan.org/~dagolden/CPAN-Meta-2.150005/lib/CPAN/Meta/Spec.pm), and in particular the [deprecation of `requires`](http://search.cpan.org/~dagolden/CPAN-Meta-2.150005/lib/CPAN/Meta/Spec.pm#requires) in favor of [`prereqs`](http://search.cpan.org/~dagolden/CPAN-Meta-2.150005/lib/CPAN/Meta/Spec.pm#prereqs).  You can see in `FPM::Package::CPAN` that dependencies are [determined on the basis of the `requires` key](https://github.com/jordansissel/fpm/blob/390ee71676be04dac0ab5858e1e73ee17bff8c73/lib/fpm/package/cpan.rb#L136-L137); this is what will need to change in order for dependency autodetection to function again.

**Comment by liger1978** [comment]
I've put in pull request #1178 which fixes this issue.  Please review and merge,
