### ISSUE TITLE
Latest fpm 1.6.3 fails to install on CentOS6: "ruby-xz requires Ruby version >= 1.9.3"

### ISSUE THREAD

**Issue by cdrx** [jordansissel/fpm#1192]
I think this was fixed in #1090 / #1132 to make ruby-xz load lazily, but as it is still listed as a dependency for the fpm gem it won't install on older CentOS systems

**Comment by iRichLau** [comment]
hi. i am running fpm 1.6.2 and this is still failing. 

fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/gem install --version 1.6.3 --include-dependencies --user-install --no-rdoc --no-ri fpm", "failed": true, "msg": "WARNING:  You don't have /root/.gem/ruby/1.8/bin in your PATH,\n\t  gem executables will not run.\nERROR:  Error installing fpm:\n\truby-xz requires Ruby version >= 1.9.3.", "rc": 1, "stderr": "WARNING:  You don't have /root/.gem/ruby/1.8/bin in your PATH,\n\t  gem executables will not run.\nERROR:  Error installing fpm:\n\truby-xz requires Ruby version >= 1.9.3.\n", "stdout": "INFO:  `gem install -y` is now default and will be removed\nINFO:  use --ignore-dependencies to install only the gems you list\n", "stdout_lines": ["INFO:  `gem install -y` is now default and will be removed", "INFO:  use --ignore-dependencies to install only the gems you list"]}

any ideas on how i would be able to fix it?

**Comment by MartinMikita** [comment]
I have found a workaround solution.

1. installing fpm 1.4.0 fails with `json requires Ruby version ~> 2.0`
2. installing the latest fpm fails with `ruby-xz requires Ruby version >= 1.9.3`

But, installing first the latest (fails) and then 1.4.0 version succeed!

Command: `gem install fpm --no-ri --no-rdoc || gem install fpm --no-ri --no-rdoc --version 1.4.0`

**Comment by DesktopMan** [comment]
I just ran into this issue while building in a CentOS 6 Docker container so here's a friendly reminder that it still occurs.

**Comment by 6minguez** [comment]
I found another solution that works also for newer versions of fpm (I used 1.11.0).
What I do is update Ruby version to 2.0.0 and then install fpm.
Here you have the code (used in a docker container from centos:6):
`yum install -y make ruby-devel rpm-build rubygems
  yum groupinstall -y 'development tools'
  command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
  curl -L get.rvm.io | bash -s stable
  source /etc/profile.d/rvm.sh
  rvm reload
  rvm install 2.0.0
  gem install fpm --no-ri --no-rdoc --version 1.11.0
  ln -s /usr/local/rvm/gems/ruby-2.0.0-p648/wrappers/fpm /usr/local/bin/fpm`
The link is for making fpm work in the docker not interactively because when you update ruby with rvm, fpm is install in that path.

**Comment by markusdd** [comment]
whoever stumbles across this because he has to package something on this ancient OS, I ttok the steps from above which did not work for me anymore and modified them like this to install latest fpm:

```sh
yum install -y make ruby-devel rpm-build rubygems
yum groupinstall -y 'development tools'
command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm reload
rvm install 2.7.2
gem install fpm 
ln -s /usr/local/rvm/gems/ruby-2.7.2/wrappers/fpm /usr/local/bin/fpm
```

**Comment by jordansissel** [comment]
I think this issue is fixed now :)

#1796 removed the `ffi` dependency. Any ffi version v1.13.0 or newer should work. Let me know if this is not the case.
