### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by zzeroo** [jordansissel/fpm#1735]
What's the status of this project? I mean >550 issues and approx. 80 PR speaks for itself. Sorry if this question was asked before, my quick search was not helpful.

**Comment by jordansissel** [comment]
Some projects close issues and PRs due to age, but I don’t do that.

As for status, the project works, but lately new changes are slow to
incorporate partly due to lack of time for me to test and evaluate these
things.

If you have an issue that you want addresses, commenting on the open issue
(or opening a new one) is a great way to start :)

For new or open PRs, help is appreciated by testing the PR to see if it
works as described and leaving feedback on that PR in a comment. I’ll
usually merge things if I see they’ve been evaluated by the community.

**Comment by BartKoppers** [comment]
I fully understand your  time-constraints on Bugs.

Some PR code changes are very simple, so I just did a review I can follow (#1738). 

Sorry for asking, but -  as a relative beginner in Github - how can 'we' (or: I) help here best....

(A number of very old PR's are not closed and/or are very big.  For example: Nuget support #704 is open (and big). Reading through, I see that you'd want to fork or branch it away).
