### ISSUE TITLE
fpm : File not found

### ISSUE THREAD

**Issue by wayneFly** [jordansissel/fpm#1773]
Hello Everyone:
    An error occurred when I used fpm。
error message：
  File not found: /tmp/package-rpm-build-225ce339eb2159ce3df425346f024af6db608adcebac2488f43d60d9c428/BUILD/node_modules/figlet/importable-fonts/Patorjk's?Cheese.js", :level=>:info}
So，What to do when special symbols cannot be avoided in the file name？

**Comment by jordansissel** [comment]
I'm not exactly sure how best to solve this right now, but I can talk through some of the history --

For starters, rpm SPEC files have problems when filenames (as listed in the spec) include spaces quotation marks, etc. FPM has some workarounds for this as shown in this method: https://github.com/jordansissel/fpm/blob/50ca2bfd052055ac3529627e98274215a63cec28/lib/fpm/package/rpm.rb#L187-L202

In this case, it seems like fpm is using a wildcard `?` for the space in "Patorjk's Cheese.js" and rpmbuild is failing, likely due to the single-quote? I'm not sure... 

I'll do some tests and see what I can learn.

**Comment by jordansissel** [comment]
Testing notes follow --

Tested with a file in `/tmp/test/jordan's cheese.txt`

```
bin/fpm --edit --verbose -s dir -t rpm -n example /tmp/test
```

The part of the rpm SPEC `%files` section looks like this:
```
%files
%defattr(-,root,root,-)

# Reject config files already listed or parent directories, then prefix files
# with "/", then make sure paths with spaces are quoted. I hate rpm so much.
/tmp/test/jordan's?cheese.txt
```

**Comment by jordansissel** [comment]
Test results on various file names:

* Fails: `/tmp/test/jordan's?cheese.txt` :: "File not found: <redacted>/jordan's?cheese.txt"
* Fails: `/tmp/test/jordan's cheese.txt` :: "File must begin with "/": cheese.txt"
* Success!: `/tmp/test/jordan\'s?cheese.txt` :: ✅

**Comment by jordansissel** [comment]
Good news, I think! A small code change makes this work: https://github.com/jordansissel/fpm/pull/1774

Testing:

```
% bin/fpm -s npm -t rpm figlet
Created package {:path=>"node-figlet-1.5.0-1.x86_64.rpm"}

% rpm -qlp node-figlet-1.5.0-1.x86_64.rpm| grep Cheese
/usr/local/lib/node_modules/figlet/fonts/Patorjk's Cheese.flf
/usr/local/lib/node_modules/figlet/importable-fonts/Patorjk's Cheese.js
```

**Comment by wayneFly** [comment]
Thank you very much.
Perfectly solved my problem.
