### ISSUE TITLE
Please use dpkg tools to build .deb when available

### ISSUE THREAD

**Issue by bigon** [jordansissel/fpm#409]
Hello,

I'm currently thinking about package fpm for debian and include it in the official archive.

I got one objection about the fact that it's completely bypassing dpkg to generate the package (see: http://bugs.debian.org/cgi-bin/bugreport.cgi?msg=22;bug=688896)

Do you think it could be possible to call the native dpkg (dpkg-deb -c) when it's installed on the machine?

**Comment by jordansissel** [comment]
@vincentbernat I'm open to discussing the pros/cons of Debian including fpm upstream. Debian probably still has political barriers (humans) as in https://bugs.debian.org/cgi-bin/bugreport.cgi?msg=22;bug=688896, but I will listen to a proposal and am willing to accept it.

I'm more open these days because:
* Most recent distros ship with a modern Ruby
* fpm isn't releasing as much as it was 3+ years ago

**Comment by jordansissel** [comment]
Actually I'll move my comment to a new issue since this one was about using dpkg instead of fpm's current internals.
