### ISSUE TITLE
Get specfile after/instead of rpm

### ISSUE THREAD

**Issue by stepps** [jordansissel/fpm#866]
I am building some packages for attic, a python package. 
Fpm is doing a fine job at that, but I would like to edit the .spec files and archive them.
I read that fpm uses rpmbuild to make rpm packages, so I guess the specfile must exist at some point.
Making a srpm would work just as well.

**Comment by jordansissel** [comment]
@stepps  the rpm spec fpm generates is only an accident. It's a symptom of the way fpm builds rpms using rpmbuild. rpmbuild requires a spec, and therefore fpm creates one.

However, fpm does quite a bit of operating outside of this spec that cause the spec to be useless outside of fpm.

If you really wish to experiment with this, you can see the spec by running fpm with the `--edit` flag. The srpm is similarly useless because there is no "source" in fpm's generate rpm spec.

This is a common request, but the rpm spec fpm generates continues to be not useful outside of fpm. It's also worth noting that fpm is moving away from rpmbuild because it is burdened by many bugs and awkward behaviors, and once that happens, there will be no rpm spec generated.

**Comment by stepps** [comment]
Well, I discovered that python does what I am looking for already, without third party apps. 

python3.4 setup.py bdist_rpm --spec-only

**Comment by sergiomb2** [comment]
> If you really wish to experiment with this, you can see the spec by running fpm with the `--edit` flag. The srpm is similarly useless because there is no "source" in fpm's generate rpm spec.
> 
> This is a common request, but the rpm spec fpm generates continues to be not useful outside of fpm. It's also worth noting that fpm is moving away from rpmbuild because it is burdened by many bugs and awkward behaviors, and once that happens, there will be no rpm spec generated.

Well `--edit` is useful to see that fpm use an almost empty spec :smile:  , but anyway is one help to build the proper spec for the package that we want convert from .deb 

Thanks
